# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_places', models.CharField(choices=[('IN', 'Indoor'), ('OUT', 'Outdoor')], default='Indoor', max_length=9)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Table/%Y/%m/%d')),
                ('available', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TableDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gallaryimage',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='table',
            name='description',
            field=models.ManyToManyField(to='homepage.TableDescription'),
        ),
    ]
